### ISSUE TITLE
Overide default "sort" options

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [molecularbiodiversity/rad-loci#4]
I am trying to install rad-loci (0.3) for someone who'll be running it within
a GridEngine (Son of GE) environment.

Most of the bare "sort" invocations within the rad-loci script pickup the
`$TMPDIR` variable that gets set by the GridEngine, but which, on my 
systems isn't meant for the size of temporary files that rad-loci is producing,
and as such I can see that the process is bombing at an early stage

```
Merge counts/filter minimum occurrences: Mon Mar 14 14:17:51 NZDT 2016
sort: write failed: /tmp/30216.1.admin_06.q/sortak6SXK: No space left on device
```

The sort untility on our systems (GNU sort) would allow for the overiding of the
use of `$TMPDIR`, the " -T --temporary-directory=DIR option", as well as allowing
for compression of the temporary files, the  "--compress-program=<PROG>" option.

I was wondering if rad-loci could be altered to allow for some extra settings that
would permit the local site to add such overrides , eg

```
SORT_COMPRESS="--compress-program=/usr/bin/bzip2"
SORT_TMPDIR="--temporary-directory=./"
SORT="/bin/sort $SORT_COMPRESS $SORT_TMPDIR "
```

and the use `${SORT}` where you currently a bare "sort".

This would be akin to the defining of system utility macros at the top of
a lot of Makefiles out in the wild, so that local sites can override default 
behaviours.

I am assuming the override values could be passed in from the settings.conf
file for any given run, and if not set. then the the rad-loci script would just define 
them as empty, and  simply see the default operation continue.

I am currently running a modified version of rad-loci that doesn't read from
settings.conf but places the three lines above in the modfied version and
can see that it's doing what I expected it to, ie writing sort's temporary files 
to the local GridEngine work directory, and compressing the files with bzip2

```
$ ls -otr
total 84496
-rw-rw-r--. 1 buckleke     2108 Mar 11 13:49 settings.conf
drwxrwxr-x. 2 buckleke     4096 Mar 14 14:58 samples/
drwxrwxr-x. 2 buckleke    12288 Mar 14 15:22 fasta/
-rw-rw-r--. 1 buckleke        0 Mar 14 15:23 test_cnt121.fa
-rw-------. 1 buckleke 84865045 Mar 14 15:31 sortoKZORB
-rw-------. 1 buckleke  1515520 Mar 14 15:31 sortmwDzFa
$ file sortoKZORB
sortoKZORB: bzip2 compressed data, block size = 900k
```

Having said that, compression might not be much of a again !
The uncompressed size of the first 'sort' file in the run that faled was

```
1075603591 Mar 14 14:20 sorteNG8cR
```

but it'd be "nice" to have the option to use it.

**Comment by molecularbiodiversity** [comment]
Resolved by Kevin's pull request #5 (manually merged in #7)

Added to [version v0.4](/molecularbiodiversity/rad-loci/releases/tag/v0.4)
